### ISSUE TITLE
Error: no such file or directory

### ISSUE THREAD

**Issue by simonjhy** [PeterEB/quick-demo-boilerplate#8]
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/simon/work/github/quick-demo-boilerplate/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at response (/home/simon/work/github/quick-demo-boilerplate/main.js:28:41)
    at Layer.handle [as handle_request] (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at /home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:281:22
    at param (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:354:14)
    at param (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:410:3)
    at next (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:275:10)
    at middleware (/home/simon/work/github/quick-demo-boilerplate/node_modules/webpack-hot-middleware/middleware.js:26:48)
    at Layer.handle [as handle_request] (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:317:13)
    at /home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/simon/work/github/quick-demo-boilerplate/node_modules/express/lib/router/index.js:335:12)

**Comment by PeterEB** [comment]
What is your `webpack` version?
